// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOxeWhLI1eymSuFM2tm1Y9LSLs3JZvqk',
    appId: '1:430571778122:web:ccaad748569e2bec15f6b3',
    messagingSenderId: '430571778122',
    projectId: 'edify-8bca0',
    authDomain: 'edify-8bca0.firebaseapp.com',
    storageBucket: 'edify-8bca0.firebasestorage.app',
    measurementId: 'G-0RGNKP9XZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLdV1k3u8YpAD0tWygVUQIlEQOkro6eU',
    appId: '1:430571778122:android:4058eaf6c5941fda15f6b3',
    messagingSenderId: '430571778122',
    projectId: 'edify-8bca0',
    storageBucket: 'edify-8bca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg3MRapEjjJbJ3OtMXy4JAEasYGZLTFNE',
    appId: '1:430571778122:ios:592810168f49270e15f6b3',
    messagingSenderId: '430571778122',
    projectId: 'edify-8bca0',
    storageBucket: 'edify-8bca0.firebasestorage.app',
    iosBundleId: 'com.example.edify',
  );
}
